// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVbV2-u8B1oqXH74myIS11Dwf-3PMg3hQ',
    appId: '1:719846166270:web:c219a26a603be108acdfaf',
    messagingSenderId: '719846166270',
    projectId: 'pemesananmakanan-67326',
    authDomain: 'pemesananmakanan-67326.firebaseapp.com',
    storageBucket: 'pemesananmakanan-67326.appspot.com',
    measurementId: 'G-C7QGNZ9SC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLlXCW26I0GWSVgM_SC5VarrJxwp7TBIw',
    appId: '1:719846166270:android:b000853c45b77d13acdfaf',
    messagingSenderId: '719846166270',
    projectId: 'pemesananmakanan-67326',
    storageBucket: 'pemesananmakanan-67326.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv9zvzCcfpA1BO7PKJyDWRQ2fvlouNetM',
    appId: '1:719846166270:ios:4e987a1f0875e04facdfaf',
    messagingSenderId: '719846166270',
    projectId: 'pemesananmakanan-67326',
    storageBucket: 'pemesananmakanan-67326.appspot.com',
    iosBundleId: 'com.example.pemesananMakanan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv9zvzCcfpA1BO7PKJyDWRQ2fvlouNetM',
    appId: '1:719846166270:ios:4e987a1f0875e04facdfaf',
    messagingSenderId: '719846166270',
    projectId: 'pemesananmakanan-67326',
    storageBucket: 'pemesananmakanan-67326.appspot.com',
    iosBundleId: 'com.example.pemesananMakanan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVbV2-u8B1oqXH74myIS11Dwf-3PMg3hQ',
    appId: '1:719846166270:web:f2aaf9a972437771acdfaf',
    messagingSenderId: '719846166270',
    projectId: 'pemesananmakanan-67326',
    authDomain: 'pemesananmakanan-67326.firebaseapp.com',
    storageBucket: 'pemesananmakanan-67326.appspot.com',
    measurementId: 'G-VBDD8CS4T9',
  );
}
